# Generated by Django 5.0.7 on 2024-08-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodStay_app', '0002_remove_custom_student_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room_details',
            new_name='RoomDetails',
        ),
    ]
