# Generated by Django 5.0.7 on 2024-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodStay_app', '0003_rename_room_details_roomdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='Monthly_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='No_of_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='Room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
