# Generated by Django 5.0.7 on 2024-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodStay_app', '0004_alter_roomdetails_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='Monthly_fee',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='No_of_beds',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='Room_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
