# Generated by Django 5.0.7 on 2024-08-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodStay_app', '0006_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GoodStay_app.roomdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GoodStay_app.custom_warden')),
            ],
        ),
    ]
