# Generated by Django 5.0.7 on 2024-08-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodStay_app', '0007_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='date_in',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='check_in',
            new_name='date_out',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='check_out',
        ),
    ]
