# Generated by Django 5.0.7 on 2024-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodStay_app', '0008_rename_date_schedule_date_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
