# Generated by Django 5.0.7 on 2024-08-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodStay_app', '0010_rename_user_schedule_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('notice_heading', models.CharField(blank=True, max_length=250, null=True)),
                ('notice_details', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
