# Generated by Django 5.0.7 on 2024-08-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodStay_app', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notice_details',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
