# Generated by Django 5.0.7 on 2024-08-09 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodStay_app', '0012_alter_notification_notice_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user1',
            new_name='user',
        ),
        migrations.AddField(
            model_name='custom_warden',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
